### ISSUE TITLE
Strange shadow in app shortcuts (Android O)

### ISSUE THREAD

**Issue by Arkanas1** [Deletescape-Media/Lawnchair#134]
![screenshot_20170705-174319](https://user-images.githubusercontent.com/29924801/27873619-0e2e5ab2-61ad-11e7-99ef-74353843ce1d.jpg)

**Comment by Dondrejohnson5** [comment]
How were you able to get square icons? Is there an icon pack you have to buy, or is it free?

**Comment by Dondrejohnson5** [comment]
Italian
Come hai potuto ottenere icone quadrate? C'è un pacchetto icona che è necessario acquistare o è gratuito?

**Comment by Arkanas1** [comment]
I have the latest android o beta version on my Nexus device, the developer preview 3 and the icons are square by default! I didn't use any icon pack.

**Comment by Dondrejohnson5** [comment]
Oh

**Comment by edisso10018** [comment]
I thought this was fixed in 238?

"Fix shortcuts font having a weird shadow"

**Comment by Arkanas1** [comment]
It seems like it wasn't, i have the latest 255 version.

**Comment by edisso10018** [comment]
See closed Issue #81 "Weird font in shortcuts"

I've already commented there.

**Comment by fonix232** [comment]
We are aware of this issue still existing, I've reopened #81. Please let's continue discussion there!
