### ISSUE TITLE
Bug: various Launchair shortcuts don't work

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Deletescape-Media/Lawnchair#1495]
## Description
When choosing any of those, nothing occurs:
"Google global search"
"Voice search"
"open app search" (this doesn't even have a special icon)

## Expected Behavior
Each should do something.

## Actual Behavior
Nothing.

## Steps to Reproduce
1. Choose to create each of those shortcuts and run them

## Environment
* Device: Pixel 2
* Android version: 9.0
* Launcher version: 1957 , from here:
https://www.apkmirror.com/apk/deletescape/lawnchair/lawnchair-2-0-1957-ci-alpha-release/
* Rom:Stock 

## Logcat
Attached video and Logcat
[files.zip](https://github.com/LawnchairLauncher/Lawnchair/files/3076007/files.zip)

**Comment by RikKoedoot** [comment]
I can confirm this issue

**Comment by RikKoedoot** [comment]
I have recorded the behavior of all shortcuts: https://photos.app.goo.gl/ZhLmC9cKgVQsRmWs7 https://del.dog/uhowiwused 
This is the log of the crash in the recording

**Comment by AndroidDeveloperLB** [comment]
@rickkode Seems to be the same as mine, no?

**Comment by divadsn** [comment]
@AndroidDeveloperLB Yes, that bug is known and confirmed.

**Comment by AndroidDeveloperLB** [comment]
ok good to know.

**Comment by suphon-t** [comment]
This should be fixed.

**Comment by AndroidDeveloperLB** [comment]
What is "This" ? Was the bug fixed?

**Comment by suphon-t** [comment]
Yes. Of course.

**Comment by AndroidDeveloperLB** [comment]
@paphonb OK I've tested now.
"Google global search" - renamed to "open global search", yet it shows the icon of Google. Does it auto-change if I switch to another ?
"Voice search" - Still doesn't do anything.
"open app search" - works, but has the default icon:

![image](https://user-images.githubusercontent.com/5357526/61735365-82067a00-ad8c-11e9-9479-33f9722e8e15.png)

Tested on version 2.0.2325-ci-alpha , version code 2325  

BTW, I've noticed it has news feed built it.
I thought it requires an additional APK for this, no? And for some reason it's not dark like the rest of the OS, and I can't find how to make it dark. How come?
