### ISSUE TITLE
[BUG] Weather no longer displayed on "At a Glance"

### ISSUE THREAD

**Issue by ianmlunaq** [Deletescape-Media/Lawnchair#3657]
### Describe the bug

A couple days ago the At a Glance widget stopped displaying the current weather. It had been working correctly this past year that I've been using Lawnchair, but it suddenly disappeared and I have no idea why. Everything else seems to work correctly, it'll show me the battery status, and Now Playing. I've tried turning the weather off and on individually on the widget, I've tried turning the entire widget off and on, I've tried restarting the launcher and restarting my phone, and I've tried reinstalling the launcher, all to no avail. I'm sorry that I can't provide any more details, but any help would be appreciated.

### Steps to reproduce

1. I have no clue, I'm so sorry.

### Expected behavior

The expected behavior is that the At a Glance widget would show the current weather.

### Screenshots

![Screenshot_20231010-093916](https://github.com/LawnchairLauncher/lawnchair/assets/55558104/8dc2842e-eeb6-4e8b-bd12-07867e5e53e3)

### Device information

- Device: Google Pixel 5a
- OS: stock ROM Android version 13, security update August 5, 2023
- App version: 12.1.0 Alpha 4

**Comment by KTibow** [comment]
Google app updated their At A Glance, causing Lawnchair's to stop working
Try disabling Lawnchair's and adding Google's At A Glance widget

**Comment by ianmlunaq** [comment]
> Google app updated their At A Glance, causing Lawnchair's to stop working
> Try disabling Lawnchair's and adding Google's At A Glance widget

I see, thank you.

**Comment by jayadev8322** [comment]
Problem solved?

**Comment by ianmlunaq** [comment]
> Problem solved?

Sort of. What I understand is that due to an update to the google app that introduced a redesigned "at a glance" widget, the integrated "at a glance" in Lawnchair just can't access or display the weather information. So I just use the new google at a glance widget instead of Lawnchair's. But I guess there is still the problem of Lawnchair's widget being slightly broken now.
![Screenshot_20231011-081950](https://github.com/LawnchairLauncher/lawnchair/assets/55558104/9fb3aad3-86fb-4288-8d50-76a617f45540)

**Comment by tushar1998** [comment]
Same issue on my s23 ultra lawnchair 12.1

**Comment by st0neh** [comment]
I'm not sure that having to use a completely different Google widget is exactly a "fix" for the at a glance in Lawnchair being broken. Why would you close this lol?

**Comment by KTibow** [comment]
It's Google's fault, and we don't know if this is even possible to fix

**Comment by st0neh** [comment]
So the plan is just to ignore it and tell people to use a Google widget?

That's a pretty lame response.

**Comment by KTibow** [comment]
Don't blame me, I'm just a random Lawnchair user

**Comment by AndersonARS** [comment]
Same problem on Motorola moto g 5G plus Android 11. It started after updating the Google app. Try using the beta version of it without success.

**Comment by st0neh** [comment]
Thanks to whoever opened this. It's the one thing I'm missing.

**Comment by forestation** [comment]
The Google At A Glance isn't a good alternative since it takes up more space on the home screen, and it doesn't allow you to click  on the date to open the calendar. Hope Lawnchair can fix its own At A Glance soon.

**Comment by KTibow** [comment]
Clicking on the date works fine for me

**Comment by forestation** [comment]
> Clicking on the date works fine for me

It did not work earlier today, though it does work now. When I tried earlier, clicking on any part of Google At A Glance took me to Weather.

**Comment by st0neh** [comment]
Disclaimer I'm no programmer but I did manage to dig around and find that

lawnchair/src/app/lawnchair/smartspace/provider/SmartspaceWidgetReader.kt

Appears to contain a bunch of weather related code including the URL it gets the weather from (https://www.google.com/search?q=weather), if this helps in any way.

**Comment by GregLiv** [comment]
Had the same issue, OnePlus 7t pro, lawnchair 12.1.0 Alpha 4. I uninstalled Google app updates and re-updated Goggle app via playstore, weather is back to at a glance now.

**Comment by tushar1998** [comment]
@GregLiv confirmed the above method works many thanks 👍

**Comment by forestation** [comment]
@GregLiv that solution worked on Samsung Galaxy Tab. Brilliant, thank you!

In case anyone can't remember how to uninstall updates to built in apps, it's under Manage Apps & Devices in the Play Store app.

EDIT: Unfortunately that solution worked for less than an hour. The weather has disappeared again 🙁

**Comment by st0neh** [comment]
I suspect the reason it's working then failing again may be due to the Google app being reset to the old weather page when you uninstall updates.

As soon as your Google app switches to the newer weather page, it kills the Lawnchair at a glance weather.

**Comment by forestation** [comment]
I reinstalled the Google app updates right away, and At A Glance still worked. It took a while (but < 1 hr) for it to stop working again. 

By the way it's not just that the weather disappears from the Lawnchair At A Glance. Take a look at the screenshot in @ianmlunaq's post above, you can see that even if you manually install the stock Android At A Glance, it doesn't look right - I think it might be an older version? 

The current Android At A Glance widget doesn't have that black gear icon on the right. When @GregLiv's fix above briefly worked, I was seeing the correct current display.

**Comment by st0neh** [comment]
I just tested and when the weather disappeared from at a glance, I opened weather and saw it flip from the old to the new layout.

For now I'm using Smartspacer to get something close to the Lawnchair at a glance widget at least.

**Comment by forestation** [comment]
As of yesterday the "fix" whereby we manually add the stock Android At A Glance widget no longer works. I had added widget to the home screen, but it disappeared yesterday and cannot be added back.

**Comment by st0neh** [comment]
Google also broke the new at a glance widget in the last couple days too.

Fun times.

**Comment by forestation** [comment]
> Google also broke the new at a glance widget in the last couple days too.
> 
> Fun times.

It did? Seems to be working fine on my Pixel phone.

**Comment by st0neh** [comment]
https://cdn.discordapp.com/attachments/409149581348306946/1176647323087028314/Screenshot_20231121-141615.png?ex=656fa136&is=655d2c36&hm=6d5b0a2727c489017087247c92c641d3b69384235c3e7124e506f65d7719c4c3&

If I uninstall updates for the Google app it works fine until the Google app updates again.

**Comment by forestation** [comment]
> https://cdn.discordapp.com/attachments/409149581348306946/1176647323087028314/Screenshot_20231121-141615.png?ex=656fa136&is=655d2c36&hm=6d5b0a2727c489017087247c92c641d3b69384235c3e7124e506f65d7719c4c3&
> 
> If I uninstall updates for the Google app it works fine until the Google app updates again.

Hmm. My Pixel is on the latest version of the Google app (and Google Play and Security Updates) and I've had no issues.

**Comment by st0neh** [comment]
Yeah it's a weird one. It works when the Google app says it has 5 widgets, it fails when the Google app says it has 6 widgets.

**Comment by forestation** [comment]
I just realized I've been mixing up a couple of things. I'll try to clarify below: 

On Pixel phones, the stock At A Glance isn't a widget per se. It's a built-in feature of the Home screen and can't be uninstalled, though it can be disabled. When Lawnchair used to work properly, it came with this feature as well.

There is a separate widget called the **Google Assistant** At A Glance listed under the Google app. It looks and behaves a little differently than the stock At A Glance on Pixel phones. Until yesterday this widget could be added to Lawnchair, but not any more. 

(You said the widget was broken by Google yesterday, but I just installed it on my Pixel and it seems to be working fine. I have 6 widgets listed under Google btw.)

Whatever Google is doing seems to have caused Lawnchair to be unable to display either version of At A Glance -- the stock Pixel At A Glance feature or the Google Assistant At A Glance widget.

**Comment by st0neh** [comment]
Oh I know the difference, I was just saying that Google somehow managed to break their new widget with Google app updates too.

**Comment by forestation** [comment]
You might've known the difference, but I don't think everyone else knew what we were talking about.

The Google widget isn't broken for me.

**Comment by st0neh** [comment]
It works for a while for me, then just completely dies.

Absolutely nothing else changed on my phone between it working fine and it being busted other than a Google Play system update and the Google app updating.

**Comment by st0neh** [comment]
https://cdn.discordapp.com/attachments/409149581348306946/1176680126327554110/Screenshot_20231121-162632.png?ex=656fbfc3&is=655d4ac3&hm=0aa488a578f0a8cdd7c199d57a9b6b438c25b67fec07896e533889d75b103aa5&

And now it looks like this.

What the hell is going on lol.

**Comment by frstycodes** [comment]
Uninstall updates for the google app from settings and it'll work again

**Comment by kymerea** [comment]
> Uninstall updates for the google app from settings and it'll work again

With the latest 14-dev build, that isn't necessary, this issue was fixed.

@MrSluffy correct me if I'm wrong but you fixed this right?

**Comment by st0neh** [comment]
The weather is now displaying again on the Android 14 builds.

However mine is now teeny tiny lol.

Looks like the homescreen app grid size changes the size of the built in at a glance, which is weird.

Also the widget version still doesn't work.

**Comment by MrSluffy** [comment]
> > Uninstall updates for the google app from settings and it'll work again
> 
> With the latest 14-dev build, that isn't necessary, this issue was fixed.
> 
> @MrSluffy correct me if I'm wrong but you fixed this right?

yes fixed now in latest 14-dev build

**Comment by MrSluffy** [comment]
I forgot to linked this too

**Comment by MrSluffy** [comment]
Fixed now in : 
- #3895
