### ISSUE TITLE
Can't change icons 

### ISSUE THREAD

**Issue by AndrewDallas** [Deletescape-Media/Lawnchair#4875]
### Describe the bug

Clicking on an icon to change it sends to the "home settings" instead of the icon selection page.

### Steps to reproduce

1. Go to icon and long hold , click customize 
2. Click on icon on pop up window
3. Sends to home settings page 

### Expected behavior

Should have the icon list pop up and choose icon , instead it takes me to the home settings page.

https://github.com/user-attachments/assets/f7ae8be3-9445-4183-bd68-0f39e50e58ab

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]

**Comment by 88572** [comment]
I'm also experiencing this on the Pixel 8a running latest nightly build/Android 15 QPR2

**Comment by mxKeaton** [comment]
Same here with the Poco X3 Pro, latest lawnchair nightly build, and lineageOS

**Comment by FrenchToucan** [comment]
Same on Android 14 September patch on a Pixel 9.

**Comment by rvsmooth** [comment]
Same experience while allowing the app notification dots

**Comment by RastalDev** [comment]
Yep, replicating exactly the same issue on Version 14.Dev.(#1492) on Pixel 8A

**Comment by AndrewDallas** [comment]
Is everyone still experiencing this issue out of curiosity?

**Comment by 88572** [comment]
Still happening.

**Comment by RastalDev** [comment]
> Is everyone still experiencing this issue out of curiosity?

On Nightly build, yes. 
On Beta 3 build, no.

**Comment by AndrewDallas** [comment]
@MrSluffy has anyone been able to figure out why this does this yet? Just curious! 

Thanks 🙏

**Comment by MrSluffy** [comment]
> @MrSluffy has anyone been able to figure out why this does this yet? Just curious!
> 
> Thanks 🙏

you can refer here : https://developer.android.com/jetpack/androidx/releases/navigation?hl=en#:~:text=A%20NavDestination%20can,potentially%20protected%20destination

**Comment by AndrewDallas** [comment]
> > @MrSluffy has anyone been able to figure out why this does this yet? Just curious!
> > 
> > Thanks 🙏
> 
> you can refer here : https://developer.android.com/jetpack/androidx/releases/navigation?hl=en#:~:text=A%20NavDestination%20can,potentially%20protected%20destination

This is basically a foreign language to me Mr Sluffy, what exactly is it saying?

**Comment by MrSluffy** [comment]
should fixed here 4e96bd45c9bade9fa19381a158644b6494db2c95

**Comment by c4tz** [comment]
@MrSluffy I just got this exact behaviour using the current (2025-06-06) nightly. I think this Renovate-commit: https://github.com/LawnchairLauncher/lawnchair/commit/65644e56628dddc4d47b35f7465da057057962a3 from last week re-introduced it. Maybe you should exclude the package from automated updates or set a maximum allowed version?

The latter could probably be done via [allowedVersion](https://docs.renovatebot.com/configuration-options/#allowedversions):
```json
{
  "packageRules": [
    {
      "matchPackageNames": ["androidx.navigation:navigation-compose"],
      "allowedVersions": "<=2.8.0"
    }
  ]
}
```

**Comment by SuperDragonXD** [comment]
To properly address this bug, we might need to refactor some parts of the navigation code (particularly on deep linking) instead of downgrading the library version. Reopening this issue though.

**Comment by jeffress** [comment]
Still happening, on a Pixel 9 running yesterday's Android 16 OTA update, w/Lawnchair Nightly 15.Dev.(#2281).

**Comment by SimplyAnotherAnon** [comment]
- Same issue, Android 16 (BP31.250523.006) on Pixel 8 Pro

**Comment by c4tz** [comment]
For me, this still happens using the nightly from yesterday (2025-06-20) with commit https://github.com/LawnchairLauncher/lawnchair/commit/de15b7c77a2192211ebac7ffd34a007b10e9591a.

Is there anything else I need to do besides installing that version and restarting my phone (just to be sure)?

**Comment by SuperDragonXD** [comment]
> For me, this still happens using the nightly from yesterday (2025-06-20) with commit https://github.com/LawnchairLauncher/lawnchair/commit/de15b7c77a2192211ebac7ffd34a007b10e9591a.
> 
> Is there anything else I need to do besides installing that version and restarting my phone (just to be sure)?

It should just work immediately after installing the nightly. You can try restarting your phone to see if the issue persists. If it does, please send a full screen recording + device information, so I can try to check why.

**Comment by c4tz** [comment]
I had already restarted when I commented before, so here is the video (which doesn't really show anything new):

https://github.com/user-attachments/assets/7417b727-6720-41ab-ad85-38f94e01c90f

My device is a Google Pixel 9a with the following versions:

* Android version: `15`
* Android security update: `5th May 2025`
* Google Play system update: `1st September 2024`
* Baseband version: `g5300t-241101-241226-B-12850354,g5300t-241101-24122 6-B-12850354`
* Kernel version: `6.1.99-android14-11-gd7dac4b14270-ab12946699 #1 Tue Jan 2113:39:43 UTC 2025`
* Build number: `BD4A.250505.003`

Thanks for looking into this again! :)

**Comment by autoricecooker** [comment]
Kinda odd since [de15b7c](https://github.com/LawnchairLauncher/lawnchair/commit/de15b7c77a2192211ebac7ffd34a007b10e9591a) fixed the icon picker for me.

- Device: ROG Phone 9 FE
- OS: Android 15
- Sec Update: 1 April 2025
- Kernel: 6.1.112

https://github.com/user-attachments/assets/163e791a-2213-4693-ae41-2102abaaef63

**Comment by c4tz** [comment]
Hmm, I just went into Obtainium, marked Lawnchair as "not updated" and (re-)installed https://github.com/LawnchairLauncher/lawnchair/commit/de15b7c77a2192211ebac7ffd34a007b10e9591a. Nothing inside Obtainium changed (dates and commit hash were exactly the same), but it now works as expected.

Thanks for the comment @autoricecooker and thank you for the fix @SuperDragonXD ! :)
