### ISSUE TITLE
[BUG] Widgets keep disappearing since Lawnchair 15

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [Deletescape-Media/Lawnchair#6092]
### Describe the bug

Widgets often disappear and I have to restart Lawnchair to get them to show again. This didn't happen on Lawnchair 14.

### Steps to reproduce

1. Go to home screen
2. Widgets will sometimes be missing

### Expected behavior

Widgets should always show.

### Device information

HTC U23 Pro on Android 13

### App version

Lawnchair 15 Beta 1

**Comment by Julrob199** [comment]
I dont know if this bug is related to this, but what happens to me is:

Sometimes whole pages with widgets disappear. Not just on my fairphone 3, but also fairphone 4.
I have three pages:
1. Where all my apps are (in folders)
2. Widgets page (no apps, just widgets)
3. Widgets page (no apps, just widgets)

Sometimes page 2 or 3 randomly disappears.

I dont know how to reproduce. When I recover the layout from the backup, it is ok for some days, but suddenly one of the pages disappear and I am left with 2 instead of 3 pages.

**Comment by USERMAN7** [comment]
I have the same issue but I don't know why is this happening, for example weather widget can stay while others disappear but after some time it disappears too

**Comment by Julrob199** [comment]
Addition: I have figured out that after around two weeks (in my case), the disappeared widgets appeared again. So they were not really deleted in the background, but just not considered by the app for a temporary duration.

**Comment by USERMAN7** [comment]
Oh they really do. I think issue is closed

**Comment by Julrob199** [comment]
The bug still exist, so I would leave it open.

Good that it returned, but the most be some reason be fixed, why it disappeared in the beginning.

**Comment by Comeza** [comment]
I have the same issue (or related)
Every time the system theme (dark/light) changes, all widgets disappear.
After some time, or when the theme changes again the widgets will reappear

**Comment by del-gh** [comment]
I'm having the same issue with widgets disappearing. I've been unable to determine what is triggering it for me though unfortunately, it seems pretty random. 

The quickest way I've found to get everything back is to force stop the app and launch it again.

**Comment by nickalcock** [comment]
I can confirm the existence of this bug: it's happening to me every few days (Fairphone 4, A15, but also seen when I was using A13). Anything I can do to help track it down?

**Comment by ehrw** [comment]
Keeps happening on Pixel 10 pro with A16 on Lawnchair 15 Beta 2.

Specifically two widgets ,yr.no (weather) and your calendar widget.

**Comment by DemiGeek83** [comment]
I also am experiencing this bug. Widgets randomly disappear from the home screen. Any movement on this issue? Device is Motorola Edge 50 ultra - Android 15 - Lawnchair Launcher 15 Dev 3232.

**Comment by seejgit** [comment]
Same issue on my Samsung A56 5G. Pages where my widgets should be are not appearing or keep getting deleted. A restart on the lawnchair normalizes it but it's getting tiring to restart the lawnchair over and over again.

**Comment by SiliconKnight42** [comment]
I'm brand new to Lawnchair, but I'm also experiencing this bug.  Samsung S22+ (SM-906U), Android 16, Lawnchair 15.Beta 2.
Affected Widgets include:  ToDoist, WFAA Weather, My Portfolio (stock prices).

Restarting Lawnchair does make the widgets visible again.

**Comment by dgoldstein0** [comment]
I'm experiencing this too.  Seems to affect all widgets most of the time, but I'm wondering if it's specific to certain pages already loaded because I just had it happen to my first two pages but not the third.  Widgets always seem to come back if I wait long enough but can disappear for hours.

Interestingly, toggling bed time mode on and off seemed to clear the problem just now. I wonder if night light may also impact it, will keep an eye out for that.

Lawncha 15 beta 2 on a Google Pixel 7 (Android 16)

**Comment by validcube** [comment]
This issue have been fixed in Lawnchair 15 Beta 2.1 release.

**Comment by dgoldstein0** [comment]
Sweet.  So when is that going to be released?

**Comment by del-gh** [comment]
> This issue have been fixed in Lawnchair 15 Beta 2.1 release.

I am running v15.0.0-beta2.1 installed through Obtanium and the issue seems to still be here. I've had widgets disappear twice in the last two days that required a force stop to bring them back again.

Does this issue need to be reopened, or am I mistaken that the current beta version should have fixed it?

**Comment by sashaaaaaaaaa** [comment]
same, didn't fix it for me unfortunately

**Comment by IcyT** [comment]
This issue should be re-opened. I can confirm that it's still happening on 15.Beta 3.

I was unsure what's causing it, but it was a good hint that it happens with the dark/light mode switch. For example when the battery runs low and the phone is recharged afterwards.

After my widgets were gone, I switched to dark mode and they were still gone. Then I switched back to light mode and they re-appeared.

**Comment by del-gh** [comment]
Yes still happening for me as well.

Since my last comment I've found that simply rotating the phone to landscape and back to portrait brings the widgets back.

**Comment by dgoldstein0** [comment]
still happening for me too, Lawnchair 15.Beta 3.

I think a new issue might get better attention so might open a new one in a minute

**Comment by dgoldstein0** [comment]
filed my case as #6930
